this is a general guide for brand new and returning players that aims to explain all the important systems in the game. *this is a work in progress*

* glossary
- mob = monster
- BA = battle analysis
- IED = ignore enemy defense

* monster spawn
to farm efficiently and have a more consistent rotation around the map, it is important to understand mob spawn mechanics.

each map has multiple fixed spawn locations for mobs and a maximum mob capacity. the base spawn timer is 7560ms (7.56 seconds), which means that every 7.56 seconds, the server will respawn up to 1 mob per spawn point, evenly distributing them across all the spawn points, but not exceeding the capacity.

in certain localizations of the game, it's possible to increase the capacity and lower the spawn timer, see the [[#spawn-enhancers][spawn enhancers]] section for details.

because spawn is evenly distributed across the spawn points, it's important to clear all the mobs evenly. not killing a particular platform or section of the map will result in more mobs piling up there, and less mobs spawning elsewhere, resulting in lower and lower kill counts every cycle.

the kill rate, or how many kills over time (usually kills per hour) you're getting, is the ideal way to test how good a rotation is. it's an absolute number unaffected by mob level. the in-game battle analysis now has a mob count which makes it really easy to measure this. it is recommended to do a battle analysis at least long enough to cycle all your skills. remember that a short BA like 6 minutes can be easily inflated by starting it as late as possible and stopping it as early as possible to slip in an extra spawn cycle worth of mobs, which could easily push for example 1670 kills to 1700 making it look like a 17k kills / hr BA. the spawn cycles not precisely aligning to the 6 minutes mark also contributes to inflating the BA

intuitively, higher mob capacity and spawn count equals better kill rate as long as you can clear the map. you can calculate the theoretical maximum kills per hour (assuming you full clear every cycle) by doing ~3600 / 7.56 * min(capacity, spawnCount)~ , where 3600 is 1 hour in seconds, 7.56 is the spawn timer in seconds, ~capacity~ is the mob capacity for the map and ~spawnCount~ is the number of spawn points. because each spawn point can spawn at most 1 mob per cycle, if you full clear you will be limited by spawn point count even with higher mob capacity. in this [[https://www.youtube.com/watch?v=GMmhd2npvdQ][example of wild hunter with frenzy totem full clearing at CLP]] , you can see that even though frenzy totem increases the mob capacity, they still only get 20 kills per cycle.

*there is an exception to this*: maps with mobs that spawn other mobs, such as the tranquil erda at below the cave, will not respect that formula. assuming the extra mobs are enough to reach capacity after the first cycle, you should probably use the capacity and ignore spawn count

at base spawn the sweet spot for optimal farming is usually a rotation that can full clear the map slightly faster than the spawn timer, so that you're evenly killing everything but you're also not waiting for spawn too long. ideally, you want to have a consistent movement cycle that lines up with the spawn timer where you briefly wait for spawn always at the same key positions. depending on class, rotations can have multiple movement cycles that are being rotated because of different cooldowns being up. [[https://youtu.be/KR6iIgiYnWk][here's an example]] of a rotation that has 3 movement cycles and alternates them like: 123123

at base spawn, it is very punishing to not sync your movement with the spawn timer: if your rotation is not circular, all the mobs that respawn behind you will not be killed until the next cycle, meaning that they are wasted kills that you could've gotten

on very fast spawn (such as frenzy totem), the concept of a cycle is much more blurry as it's very difficult to keep up with the spawn timer so the kill rate usually doesn't reach the theoretical maximum except for very small maps

** monster spawn resources
- [[https://seollal.tistory.com/category/%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC/%EC%82%AC%EB%83%A5%ED%84%B0][korean website with mob spawn counts for arcane river and grandis]] - supposedly measured from watching grinding videos and testing in-game. some numbers are wrong such as shadowdance hall 2 but for the most part it seems accurate. it's also not clear if the bigger 40+ mob maps are accurate since other sources mention that mob capacity can't exceed 40
- [[https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5lCPppCU8Mc10n21X26twPaN6npLU_wqnYuBomtQyRysjlALs5_qcDV0RtLSIVOlHwGTGV1Cxq62Y/pubhtml?gid=481997935&single=true][spreadsheet with arcane river mob capacities]]

* meso farming
grinding is a popular way to get meso. you have to grind for levels for hundreds of hours, so setting yourself up to farm meso along the way is a good idea as you will get better value for your time rather than just pure EXP. besides meso, you will also get useful or valuable drops such as: nodestones, droplets, honor, cubic blades, unrelenting flames, familiars. some people even go as far to intentionally slow their leveling down so they can meso farm longer before they outlevel a map.
** sources of meso obtained
the cap for meso obtained is 100% from equip potentials. inner ability, monster life, legion grid, use coupons, class passive (shadower) go above this cap. this means that shadowers can achieve 20% higher meso obtained than any other class thanks to their passive.
*** inner ability
| rare      |   3-5% |
| epic      |  8-10% |
| unique    | 13-15% |
| legendary | 18-20% |
*** potentials
on Face Accessory, Eye Accessory, Ring, Earring, Pendant at legendary
| item level | drop rate |
|       0-30 |       10% |
|      31-70 |       15% |
|        71+ |       20% |

event rings are a free way to get a legendary meso/drop accessory. they can be obtained during events, usually by coin capping. the reason they are a free legendary potential is that there are event ring meister/purple cubes that you can buy in event shops, usually for coins, as well as occasional legendary event ring potential scrolls.
*** bonus potentials (non-reboot only)
on everything except weapon, secondary, emblem at legendary
| item level | drop rate |
|       0-20 |        2% |
|      21-50 |        3% |
|      51-90 |        4% |
|        91+ |        5% |
*** monster life (non-reboot only)
| toy              | 1-7% |
| moon bunny thief |   4% |
*** use/cash items
| legion's wealth                                               | 50%                                 |
| wealth acquisition potion                                     | multiplies your meso by 1.2         |
| twin coupon / cash 2x drop coupon (only some non-kms regions) | multiplies your meso and drops by 2 |
*** legion grid
the phantom legion piece gives 1-5% meso
|   level | meso |
|   60-99 |   1% |
|  99-139 |   2% |
| 140-199 |   3% |
| 200-249 |   4% |
|    250+ |   5% |
** meso drop rate
a lot of people fail to take the meso drop rate into account. mobs have a 60% base chance to drop meso bags. this means that if you have at least 67% drop rate you can guarantee that meso bags always drop because ~0.6 * 1.67 = 1~ .
if you don't have enough drop rate you will not get your full meso rates.
** sources of meso drop rate
*** inner ability
| rare      |   3-5% |
| epic      |  8-10% |
| unique    | 13-15% |
| legendary | 18-20% |
*** potentials
on Face Accessory, Eye Accessory, Ring, Earring, Pendant at legendary
| item level | drop rate |
|       0-30 |       10% |
|      31-70 |       15% |
|        71+ |       20% |

event rings are a free way to get a legendary meso/drop accessory. they can be obtained during events, usually by coin capping. the reason they are a free legendary potential is that there are event ring meister/purple cubes that you can buy in event shops, usually for coins, as well as occasional legendary event ring potential scrolls.
*** bonus potentials (non-reboot only)
on everything except weapon, secondary, emblem at legendary
| item level | drop rate |
|       0-20 |        2% |
|      21-50 |        3% |
|      51-90 |        4% |
|        91+ |        5% |
*** monster life (non-reboot only)
| erda  | 1-7% drop rate in arcane river |
| seruf |                             2% |
*** familiars (only some non-KMS regions)
NOTE: familiar drop rate does NOT affect meso drop rate. you need it to be meso drop rate specifically.
| tier   | line                                                      |
| common | Increase Item Drop and Meso Drop by a small amount (20%)  |
| common | Increase Meso Drop by a small amount (30%)                |
| epic   | Increases Meso Drop Rate by a large amount (100%)         |
| epic   | Increases Meso Drop Rate (60%)                            |
| unique | Increases Item and Meso Drop Rate by a large amount (60%) |
*** use/cash items
| legion's luck                                                 |                                 50% |
| 2x drop coupon                                                |                                100% |
| wealth acquisition potion                                     |                                 20% |
| twin coupon / cash 2x drop coupon (only some non-kms regions) | multiplies your meso and drops by 2 |
** cheap setup for non-reboot
since meso/drop items can be expensive, it's ideal to avoid buying meso/drop items whenever possible. this setup will put you at 118-120% meso (161-164% with the wealth potion) and 67-79% drop (when the wealth potion is active)

| meso on inner ability 1st line       | 18-20% meso                              |
| drop on inner ability 2nd line       | 13-15% drop                              |
| 4 event rings with meso potential    | 80% meso                                 |
| cheapest meso accessory you can find | 20% meso                                 |
| cheapest drop accessory you can find | 20% drop                                 |
| decent holy symbol                   | 14-24% drop                              |
| wealth acquisition potion            | 20% drop and multiplies your meso by 1.2 |

if you are on GMS or any region with familiars, you can replace the drop accessory with a common familiar that has "Increase Meso Drop by a small amount" or better, but keep in mind that if you farm a lot you will have to keep extracting familiar cards to buy familiar essence which can be annoying and if you're not farming in a map that drops familiars then you will have to spend meso to buy them from the auction house, or you just can't if you're in reboot.

if your region has cash 2x drop coupons that double your meso (twin coupons in MSEA), remember to use them

NOTE: apparently nodestone drop rate caps at 200%, so your node drops won't benefit past that
* spawn enhancers
:PROPERTIES:
:CUSTOM_ID: spawn-enhancers
:END:
the base spawn rate of the game is 7.56 seconds, or 7560 milliseconds.  however, regions outside of korea have introduced ways to speed up the spawn timer and increase the mob count. this decision has significant balance and gameplay implications since it essentially multiplies farming/exp rates and changes the meta maps for farming

** availability
- *KMS never had any spawn enhancers.* this is the reference, upstream version of the game
- *MSEA doesn't currently have any spawn enhancers.* used to have kishin (removed in 2022).
- GMS has frenzy (but it's unobtainable) and used to have wild/fury totem and kishin (both removed in 2022). *GMS Reboot no longer has spawn enhancers as of 2022*
- TMS has frenzy totem and it's obtainable
- Kanna and Kishin originally come from JMS. since I don't play JMS and don't know japanese I don't know that the current situation is in JMS with spawn enhancers

** wild totem
 this was removed from GMS in 2022 (ignition patch).

lowers spawn time by 40% and increases mob count by 50%. if you leave the map after casting, the effect will go a way. a cast lasts 2 minutes.

used to be 1800 reward points for a coupon which, once used, gives you a totem equip that expires 2 hours after using the coupon. equipping it will give you a Wild Totem skill in your beginner skill tab that you can keybind and use.

used to be able to get up to rougly 17 totems per month: 15 from reward points, 2 from daily gifts. occasionally events will give out more.
** fury totem
this is what wild totem used to be called. the transition to fury totem was supposed to lower its spawn rate but it ended up rouding to the same spawn cycle. I am not sure if the mob count ended up being the same.
** kishin
kishin is a kanna skill that *used to increase spawn rate*. kishin pre-dates wild and frenzy totem. it used to be better than frenzy spawn and got nerfed over many years. *in 2022, GMS and MSEA nerfed kishin to no longer increase the spawn rate*. I'm not sure if any region still has spawn increasing kishin, maybe JMS?

the history of kishin nerfs goes something like this:

- better than current frenzy
- worse than frenzy
- lower spawn rate even further
- add a cooldown to prevent people from afk key weighting to kishin maps. 100% uptime was achievable by proccing nightghost when you hit mobs to lower kishin cooldown. it was still possible to have a kishin mule with a combination of sticky keys, key jamming and intentionally nerfing your damage so you could hit mobs without killing them
- remove the spawn increase effect entirely and change the skill to a 10% exp passive
** frenzy totem
lower spawn time by 75% and increases the mob count by 70%. the effect stays even if you leave the map after casting. a cast lasts 10 minutes.

it used to be obtainable from gacha things such as the marvel machine and philosopher books. this was only ever available in non-reboot.

this is no longer available in GMS, but many frenzy totems remain in the game and are being traded around (usually in the black market).

*people sell frenzy totem service: you pay them to cast frenzy in your map, which is the meta to farm on regions that have frenzy.*

a frenzy totem works essentially like a wild totem, in that it's an equip and it gives you a skill in the beginner tab. however unlike a wild totem, it is a permanent equip.
** spawn cycles rounding
you can watch [[https://www.youtube.com/watch?v=CNddTLz3KQg][this video]] for more details, but the spawn time ends up rounding up or down to multiples of 1080ms.

here's what the rounded spawn cycles end up being (credits to [[https://www.youtube.com/watch?v=CNddTLz3KQg&lc=Ugz7QND6wRtjchc3yjB4AaABAg][this comment]]):

| base spawn                                                 | 7560ms  |
| wild totem                                                 | 4320ms  |
| v214 kishin                                                | 4320ms  |
| fury totem                                                 | 4320ms  |
| first kishin nerf                                          | 3240ms  |
| double cast glitched kishin                                | 2160ms? |
| current frenzy totem                                       | 2160ms  |
| pre-frenzy kishin                                          | 1080ms  |
| release day frenzy                                         | 1080ms  |
| stacking kishin and frenzy (it was possible at some point) | 0ms     |

* regional differences
there are multiple localizations of the game with significant content and gameplay differences. it's important to be aware of these differences when discussing game balance decisions coming from KMS, as they can sometimes appear nonsensical in a meta that significantly differs from KMS. this list is inteded to illustrate balance/meta difference between regions, it's not inteded to be an exhaustive list
** KMS - Korean MapleStory (April 29, 2003)
the original, upstream, reference version of the game. all core content updates are released in korea first and trickle down to other regions months later. also the most highly populated version currently
** JMS - Japanese MapleStory (December 3, 2003)
*** JMS classes
**** Kanna (mage, August 16 2012)
introduced the skill Kishin, which speeds up the respawn time and increases the maximum number of monsters in the map. as far as I know, the first spawn enhancer.

*this made farming a lot faster than intended and changed the meta for the most efficient maps*. it also pushed players to create a kanna on a second account to cast kishin for their main, a 2pc meta. *it was subsequently nerfed multiple times in GMS and MSEA until the spawn enhancement effect was completely removed in 2022*. I am unsure about the status of kishin in other regions.

link skill is 10% damage which ends up being one of the best-in-slot link skills for mobbing and bossing
**** Hayato (warrior, July 24 2012)
**** Beast Tamer (mage, July 2014)
link skill gives up to 10% crit rate and 10% boss damage
*** JMS bosses
**** Princess No
- drops Kanna's Treasure, a level 140 ring. *significant power creep: KMS doesn't have many rings that can be starforced to 22+ stars* (and all of those rings are unique equipped) so it's a power creep over KMS especially with how early it can be obtained
- drops Captivating Fragments which can be opened for a Princess No secondary weapon. these have slightly better stats than a regular secondary but the difference is negligible
**** Akechi Mitsuhide
just below normal lotus in terms of damage requirement, sizable increase in boss crystal meso income
*** JMS questlines and areas
**** Threads of Fate
comes with a mini dating sim ui with all the characters from the questline.

players have been able herb pouches much more easily than intended with a complicated setup exploiting seemingly unintended mechanics with the "ask" system. *this makes wealth acquisition potions and other items crafted with juniper berry seed oils a lot more easy to obtain than originally intended*
**** Zipangu region
Mushroom Shrine, Ninja Castle, Showa, Neo Tokyo, etc...
*** JMS events
**** Sengoku High
allows players to obtain the sengoku badge, a badge that can obtain potential. *significant power creep: KMS doesn't have any pottable badges, so it's an extra potential that they don't have*
** GMS - Global MapleStory (May 11, 2005)
- imported a lot of content from JMS, including Kanna, Hayato, Beast Tamer, Princess No, Akechi Mitsuhide, Threads of Fate, Zipangu
- imported lab server and the housing and familiar systems from TMS
- *imported +1 star force scrolls from MSEA* see msea section
- *imported pottable sengoku badge from JMS*. this event hasn't come back in years though, so it is considered an *unobtainable legacy item that gives people who got it back in the day an whole extra potential*
- *the reboot meso multiplier is 6x instead of 5x*
- *boss crystal prices are different*. in KMS, bosses before chaos papulatus are worth significantly less and bosses after that are worth more, with the endgame bosses being worth a lot more than in GMS
- *nodestone drops are untradeable*. to sell nodestones on the auction house, you have to open them and extract them to craft tradable ones.
- *daily bosses drop master and meister cubes*
- *master and meister cubes are untradable*
- *miracle time event doesn't affect non-cash cubes (such as meister, master, occult)*
- *reward points cannot be used to buy NX items in the cash shop, unlike in KMS*. there is instead a dedicated reward points shop with limited choice
- *instead of having the non-expiring buff freezers packs that KMS has, GMS has an npc called Matilda in non-reboot that sells 5 1-week buff freezers for 1m each per day.*
- *reboot buff freezers are 5m instead of 1m and they expire instead of being permanent*
- *most NX outfits expire in 90 days instead of being permanent*
- *to use 3 pets, players need to buy a pet snack with either reward points (once a month) or for NX and complete a quest*. in KMS you can immediately use 3 pets
- *spell trace fever doesn't happen every sunday*. it's every few months and it's time slots of like 2 hours over a couple days instead of a whole 24 hours like on KMS
- *equips can be hammered twice instead of once*. this adds up to a decent power creep, especially if you consider 1 extra slot of everything that scrolls for att
- *imports TMS cubes such as violet, uni, equality. these make 3line and multiple prime potentials a lot easier to obtain for non-reboot*. violet cube prime chances are much lower than in TMS and don't guarantee double primes
- *much higher tier up rate for potential, estimated to be 4-5x of KMS*
- *higher star force price than KMS (20-30% higher?)*. starforce price will be reduced by another ~20% after totem removal
- *imports breath of divinity from TMS* see TMS section
- *level 151+ items have higher potential lines, similar to the 250+ lines for ethernal equips in KMS. slight power creep*
- auto all-cure skill for pets. makes bosses like pink bean less annoying
- *no scissor of karma limit. in KMS, scissorable items will become permanently untradable once the limit runs out*
- pensalir equips don't become untradable after equipping
- lab server hasn't come back unlike in TMS, so this is *legacy power creep that new players don't have*
- you can charge a weapon with no soul and get att for it being charged as long as you used a soul enchanter on it. in KMS, you also have to apply a soul
- items can drop with bonus potential on them, making it a lot easier to transfer hammer rare or epic bonus potentials for cheap

*** GMS items
**** ghost ship exorcist badge
apparently MSEA doesn't have this. this is a pottable badge like the sengoku badge that used to be obtainable from the singapore ghost ship questline, however the area has been removed and this item is now unobtainable. *players with this legacy item have one extra potential*
**** battle-roid android (non-reboot)
*gives infinite buff freezers*. this can be obtained through gacha systems such as the marvel machine and is a very expensive purchase for the average player (like 300k NX worth of meso) I am unsure what region this item originates from
**** wondroid heart
*on non-reboot, 22 higher att than a fairy heart from spell tracing due to higher att per slot because of the higher level*. the only lvl 120 permanent heart in KMS is the liquid-metal heart and it has been unobtainable for a long time.
**** outlaw heart (non-reboot)
*major power creep: 29 higher att than a fairy heart from scrolling. also goes to 22+ stars  and gains attack so way higher stats, like 200+ total attack at 22*
**** lucid earring (non-reboot)
cash equip that gives a bind skill with a 90s cooldown. cooldown not shared with other binds. *makes bosses significantly easier since they can be bound a lot more often*
**** alien equips
the alien party quest was discontinued and removed in 2022. VIP alien accessories could be obtained from it, which are always tradable and excellent for transferable meso/drop gear in non-reboot. the pendant is 22+ starrable
**** dark totems
dark totems of darkness is an event that gives totems that give up to 15 att and 36 main stat each. *this even hasn't come back in years so these are assumed to be legacy items. MAJOR power creep, 45+ att and a lot of stat from 3 dark totems is very significant*
*** GMS spawn enhancers
- frenzy totem (non-reboot only) *major balance implications: over 2x the farming rates as KMS*
- used to have wild totem and kishin. removed in 2022
*** GMS buffs
- 24 hours *multiplicative 2x exp coupon. only works up to lvl 250. makes early leveling significantly easier.*
- used to have a multiplicative 2x drop coupon like MSEA's twin coupon. *removed in 2022 but has significantly affected non-reboot economy by doubling farming rates for years*
*** GMS classes
**** Jett (pirate)
*** GMS bosses
**** gollux
released in 2013, it introduced the gollux accessories, easily obtainable even by weak low level characters by farming the lower difficulties of the boss daily. *MAJOR power creep: superior gollux 4-set effect is 30% boss 30% ignore defense, 35 att and a bunch of stat. on non-reboot, each accessory can be scrolled with special scrolls that give 4 att per slot, much easier to obtain than premium accessory scrolls. this was so overpowered that as of 2022 these accessories are still the realistic best in slot. this makes some KMS accessories irrelevant, such as the estellia earring. it also makes the pitched boss set a lot less appealing, which is supposed to be the endgame*

it was revamped in 2020 to have a much higher damage requirement and more unforgiving mechanics. even characters that can clear normal lotus might struggle with hellux. the gear is still relatively easy to obtain for how good it is
*** GMS questlines and areas
**** monad
*removed in 2022*. this was effectively an extra daily boss (julieta) that you can do 4 times a day for extra chance of cubes. also drops boxes that give epic empress and japanese gear.
**** commerci
through denaro obtained from daily voyages and the party quests, players can purchase sweetwater accessories. this content can be easily cleared even on a weak low level character. the face and eye accessories are sometimes slightly better than alternatives because they're level 160 and have higher potential lines and staforce stats.

denaro can also be used to transpose items. see the transpose section
**** maple tour
similar to monster park but gives meso weekly. doing 7 runs is pay to win so most people do 2 runs per day which on reboot nets 380m per week at lvl 200+. for new players who get most of their meso from ursus this significantly increases meso income
*** GMS upgrade systems
**** familiars
adds the ability to summon monsters as your familiars which have stats similar to a potential on them. *major power creep: these can roll boss damage and ignore enemy defense lines. also, healing familiars allow players to heal quickly and even through heal lock boss mechanics which makes a lot of bosses a lot easier that they should be*.

the GMS familiar system is a bit different than TMS's. UI appears to be a bit different, and familiars can't roll final damage unlike in TMS. might be an older iteration of it

familiar cards only drop in morass, esfera, moonbridge, labyrinth, limina for lvl200+ areas. *this creates a huge bias to avoid other areas like sellas or the lvl 260+ grandis areas until your familiars are done even though they would otherwise be perfectly valid for farming.*
**** transposing
part of commerci. you can only transpose into sweetwater armors and accessories. the source items cannot be higher than 16 stars. one star is lost but the stats remain. so *if you transpose at 16 stars, you get a 15 star item that has the stats of a 16 star*, effectively injecting an extra star worth of stats. flame stats of the source item are maintained, so *trasponsing a flame advantaged item gets you a flame advantage flame even though sweetwater gear doesn't have flame advantage*. the source item set effect is lost and replaced by the destination set effect (only sweetwater armors have a set effect). back when tyrants were meta, this was used to give tyrant gear a set effect for a bunch of extra attack. currently, it is used to transpose accessories for the higher stats. pendant and eye accessory usually. *small power creep: a bit of extra attack and stat*
**** dark scrolls (non-reboot)
legacy 30%/70% scrolls that have a chance of destruction. some of them are better than spell tracing, for example shield scrolls for att. slight power creep, not super expensive but pretty rare

I am not 100% sure dark scrolls are non-KMS, but I couldn't find any reference to them being in KMS
**** prime scrolls (non-reboot)
very expensive and difficult to obtain scrolls that give 10 att and 3 all stats on weapons, 10 all stat on accessories and armors. barely better than 30/15% scrolling. I am not sure what region these scrolls originate from
**** X scrolls (non-reboot)
very expensive and difficult to obtain scrolls (I believe they come from marvel and philosopher books?) that give 5-7 att on pet equips and armors, 10-12 att and 5 all stat on weapons. *significant power creep as this is much easier than incredible chaos scrolls on armor, but unrealistic for most players* . I am not sure what region these scrolls originate from
**** level 3 link skills
a lot of link skills have an extra level at lvl 210 that KMS doesn't have. slight power and exp creep
**** attack speed 0
the green monster park potion allows breaking the soft cap of attack speed 2. in KMS, this is impossible. *major balance implications: classes that don't scale with attack speed are worse than intended and vice-versa*
** TMS - Taiwan MapleStory (June 1, 2005)
this region is known to have insane power creep. not knowing the language I don't know the true extent of the custom content in this region.

apparently their starforce is way more expensive than in any other region but they have ways to safeguard past 17. no idea about the details
*** TMS upgrade systems
**** familiars
adds the ability to summon monsters as your familiars which have stats similar to a potential on them. *major power creep: in TMS, familiars can roll % FINAL DAMAGE lines*.
**** lab server
a temporary server with different rules that gives a +25 att 5 block legion block and a +35 att 5 block legion block. *major power creep: 60 att total*
**** animus cube (non-reboot)
works like a black cube but you *can lock a line that you don't want to reroll*. apparently you need some etc from bosses to lock
**** reflect cube (non-reboot)
like a red cube but has a 20% chance to mirror the 1st line to the 2nd line, making it 
**** hexa/violet cube (non-reboot)
rolls 6 lines and lets you pick any 3 of them. *much higher chance of 3 lining an item than regular cubes*. in TMS, these cubes guarantees 2 prime lines on every roll. other regions such as GMS and MSEA have lower prime chances that don't guarantee more than 1 prime
**** equality cube (non-reboot)
only rolls prime lines. *multiple prime items WAY easier, especially good for things like double drop, meso, crit damage, cooldown*
**** uni cube (non-reboot)
spend cubes to select a random line, reroll line once (without spending cubes), repeat. *makes triple prime items a lot easier (equality cube double prime -> unicube 3rd prime line). also good for turning a 2l into a 3l*
**** housing system
mostly cosmetic but gives a 15% boss damage buff
*** TMS items
**** breath of divinity ring (non-reboot)
very expensive item obtainable from gachas like marvel machine and philosopher books. *makes boss mechanics a lot easier: gives a shield buff skill that lets you tank 100+% hp attacks quite often (the extra hp bar recovers as you hit the boss). it's also yet another 22+star ring that KMS doesn't have*

** CMS - China MapleStory
apparently the official chinese name is "Adventure Island Online". I don't know much about this region. some major balance critical difference that I heard about are a *lower damage cap than other regions that can be unlocked by spending money and 6 ring slots*

*** CMS classes
**** Zen (pirate)
apparently started as a Jett reskinned to have more of a martial arts theme. development of this class later stopped and creation was disabled. Zen characters were later converted to Mo Xuan in regions that had that class. MSEA just outright deleted the class and forced people to job change their Zens to other explorer pirates
**** Mo Xuan (pirate)
martial arts themed class that replaces zen in CMS and TMS
** MSEA - MapleStory South East Asia (June 23, 2005)
MSEA doesn't have a reboot server. they import some of the TMS cubes such as hexa and reflect.

has battle-roid and outlaw heart. see GMS section

has breath of divinity. see TMS section

has lucid earring and attack speed 0. see GMS section
*** MSEA buffs
**** twin coupon (non-reboot)
multiplicative 2x drop coupon which also doubles meso drops. *major balance implications: effectively doubles farming rates, including meso*
*** MSEA upgrade systems
**** +1 star force scroll (non-reboot)
up to 50% chance to gain 1 star up to 23 stars with no destruction or drops on items up to level 200. *major power creep: 23 stars becomes a lot easier*. non-reboot only
** EMS - Europe MapleStory (April 12, 2007)
in 2016, EMS was merged with GMS and all data was transfered over.

some content that was unique to EMS is forever gone, such as the veracent area. a lot of legacy items from EMS only events and content carried over to GMS, such as lord of the darkness medal (+50 att).

there were also issues migrating flames to GMS, resulting in *items being able to be flamed twice with way higher than intended stats*. apparently the flame stats were initially converted to blue stats. some of these double flamed items are still around in the auction house
** Thailand MapleStory
I don't know much about this region, other than it was shut down in 2020 and players were forced to move to MSEA and given a few gifts (but no data transfer).

* farming rotation examples
the maps are named according to GMS. to look up map names for other regions, [[https://maplestory.fandom.com][strategywiki is a good source]]

** rotation examples - base spawn
note that a lot of these are close to optimal: 1shotting, vac pet, etc. these maps are still good even with sub-optimal mobbing, as long as you take time to experiment and adjust the rotation. also ignore the exp, as multipliers are inconsistent and some of these videos are overleveled and just showing off the rotation. tl;dr you should usually /strive/ for these rates, not necessarily match them. if you have better rotations, feel free to pull request or open an issue and link them.

also keep in mind that short BA's like 6 minutes can be inflated easily. so the kill rate will usually be slightly worse over 1+h, and some BA's show a kill rate that seems slightly higher than the max theoretical.

when the mob capacity is higher than the spawn count, the first wave of the BA will have extra mobs. the last spawn cycle in a 6min BA night not exactly align with the 6min mark which also contributes to inflating the numbers. if someone is full clearing, you can safely assume they are getting the max theoretical kill rate ~3600/7.56 * mobCount~.

the mob counts are the mobs per cycle when full clearing, based on watching videos of rotations
*** vanishing journey
[[https://seollal.tistory.com/1082][mob counts (korean)]]
**** hidden lakeshore
35 mobs. this is a high arcane force map so not necessarily realistic for a brand new player to 1-shot. it's pretty much the only decent map in VJ. also note that the exp per mob is higher than other maps

full clear: 16.66k
- [[https://www.youtube.com/watch?v=f1ZfWT9WUhQ][buccaneer - 15.29k]]
- [[https://youtu.be/YVQBnuQonvE?t=48][shadower (pre-destiny) - full clear]]
- [[https://www.youtube.com/watch?v=Q4fXHIwkUTE][lara - 14.9k]]
- [[https://www.youtube.com/watch?v=nun0i3zPvJY][phantom - 15k]] - appears to have a 5s cooldown hat so don't expect to use your cooldowns that often
- [[https://www.youtube.com/watch?v=IFZnKeb5sJw][dawn warrior - 14.2k]]
- [[https://www.youtube.com/watch?v=7b4hPkf-TPM][hoyoung - 15.7k]]
- [[https://www.youtube.com/watch?v=QLEcjpSleW4][mercedes - 11.8k]]
- [[https://www.youtube.com/watch?v=LHSf9vu3FYU][corsair - 15.8k]]
- [[https://www.youtube.com/watch?v=HwBscCktvwI][kain - 13.8k]]
- [[https://www.youtube.com/watch?v=O1YF1Xdjb4Q][marksman - 14.8k]]
- [[https://www.youtube.com/watch?v=TpaDFJqOhv4][illium - 15k]]
- [[https://youtu.be/WeEOAGV3Pms?t=226][adele - 14.5+k]]
- [[https://www.youtube.com/watch?v=v6FHW1acnWE][thunder breaker - 12k]]
**** hidden cave
29 mobs. high arcane force, high exp per mob map

full clear: 13.8k
- [[https://youtu.be/WeEOAGV3Pms?t=175][adele - 12k]]
- [[https://www.youtube.com/watch?v=IKtswRNr4Xs][night walker - 13.25k]]
- [[https://www.youtube.com/watch?v=Vh8dW-kMILM][dawn warrior - 13.19k]]
- [[https://www.youtube.com/watch?v=QNa2jHIJ99g][night lord - full clear]] - 1shot assassin mark
**** below the cave
13 mobs, but each mob spawns a lantern. based on the top kill rates people are getting the effective number of mobs per cycle seems to be 25-26

full clear: 12.6k?
- [[https://youtu.be/WeEOAGV3Pms?t=87][adele - full clear]]
- [[https://www.youtube.com/watch?v=XE7a6NlpB7c][thunder breaker - 12k]]
- [[https://www.youtube.com/watch?v=L0rtSM2ToKk][blaster - full clear]]
**** above the cave
same mob count situation as below the cave

full clear: 12.6k?
- [[https://www.youtube.com/watch?v=hDdp7Qm30dg][mercedes - 11.6k]]
**** eastern cave path 2
same mob count situation as below the cave

full clear: 12.6k?
- [[https://youtu.be/TSyX2VC4JKE?t=174][lara - full clear]]
**** western cave path 2
same mob count situation as below the cave

full clear: 12.6k?
- [[https://youtu.be/WeEOAGV3Pms?t=113][adele - 12k]]
*** chu chu island
[[https://seollal.tistory.com/1090][mob counts (korean)]]
**** mottled forest 2
33 mobs. my favorite map to grind to 220. based on the dawn warrior video, the mob capacity appears to be 40

full clear: 15.7k
- [[https://www.youtube.com/watch?v=0_ZZ2lcJZSs][corsair - 15.5k]]
- [[https://www.youtube.com/watch?v=43m-WgBE7eA][blaze wizard - 15k]]
- [[https://www.youtube.com/watch?v=VODxDcBsL3M][blaze wizard - 15.5k]] alternative rotation, pre-ignition but should apply to post-ignition too
- [[https://www.youtube.com/watch?v=_0pfV1fl9Jg][dawn warrior - full clear]]
- [[https://www.youtube.com/watch?v=BmAp4Wk-msw][hoyoung - full clear]]
- [[https://www.youtube.com/watch?v=_R6LIGnLnZA][mercedes - 14.6k]]
- [[https://www.youtube.com/watch?v=hdufINpMm_s][mercedes]] alternative to the above rotation, similar kill rate. I prefer this version
- [[https://www.youtube.com/watch?v=km65vR9S19c][mechanic - 14.7k]] (no vac pet)
- [[https://www.youtube.com/watch?v=YBaZbY7TNCo][shadower - full clear]]
- [[https://www.youtube.com/watch?v=sktfcL5R-Ok][adele - full clear]]
**** within five-color hill
30 mobs

full clear: 14.28k
- [[https://youtu.be/TSyX2VC4JKE?t=453][lara - 13.3k]]
- [[https://www.youtube.com/watch?v=EoPAQUFtyUA][corsair - 14k]]
**** torrent zone 3
28 mobs. not great kill rate but higher exp per mobs than other maps. good alternative if you don't care about meso/nodes or everything else is full. also pretty lazy if you use the water

full clear: 13.3k
- [[https://www.youtube.com/watch?v=E7XJ_JSXb48][dawn warrior - 13k]]
- [[https://www.youtube.com/watch?v=q71FF5DpSq4][ark - 12.46k]]
**** torrent zone 1
28 mobs. similar to torrent zone 3 but smaller hitboxes

full clear: 13.3k
- [[https://www.youtube.com/watch?v=qAKN8KDVloI][hoyoung - 12.8k]]
- [[https://www.youtube.com/watch?v=dgizlXlswZU][kain - 12k]]
- [[https://www.youtube.com/watch?v=PY9wLfoBeL8][mercedes - 12.2k]]
**** mottled forest 3
26 mobs

full clear: 12.38k
- [[https://youtu.be/TSyX2VC4JKE?t=590][lara - 11.3k]]
- [[https://www.youtube.com/watch?v=PEZC7g-3czc][adele - 11.1k]]
*** yum yum island
[[https://seollal.tistory.com/1093][mob counts (korean)]]
**** hidden mushbud forest
24 mobs, high arcane force map. capacity appears to be 31

full clear: 11.4k
- [[https://youtu.be/TSyX2VC4JKE?t=870][lara - 11.3k]]
- [[https://www.youtube.com/watch?v=9zAHgql1KZ4][dawn warrior - full clear]] 
**** hidden illiard field
24 mobs, high arcane force map.

full clear: 11.4k
- [[https://youtu.be/TSyX2VC4JKE?t=1014][lara 11.2k]]
*** lachelein
[[https://seollal.tistory.com/1091][mob counts (korean)]]
**** chickens festival 3
38 mobs, best map by far if you can clear enough mobs per cycle.
aliases: 닭뛰3

full clear: 18.09k
- [[https://www.youtube.com/watch?v=mVB9gTThDLs][corsair - full clear]]
- [[https://www.twitch.tv/videos/1558360414][shadower - full clear (1 hour, GMS)]]
- [[https://www.youtube.com/watch?v=biXzfE3Z4-c][night lord - full clear]]
- [[https://www.youtube.com/watch?v=Q3xbQE2qaYk][mechanic - 17k]]
- [[https://www.youtube.com/watch?v=ia_YPKbV0TI][dawn warrior - 15.6k]]
- [[https://www.youtube.com/watch?v=D4kiGOiGNCU][dark knight - 14k]]
- [[https://www.youtube.com/watch?v=0Ua8NqTasNk][marksman - 16k]]
- [[https://www.youtube.com/watch?v=Zq4Ak4sabEw][marksman - 17.43k]]
- [[https://www.youtube.com/watch?v=Gnl2lbfpE3k][lara - full clear]]
- [[https://www.youtube.com/watch?v=_8drrqEgAoE][luminous - 17.5k]]
- [[https://www.youtube.com/watch?v=UgichB-Am7s][thunder breaker - 15.4k]]
- [[https://www.youtube.com/watch?v=blunbaDc6W0][hoyoung - 17.5k]]
- [[https://www.youtube.com/watch?v=fEotsFHeqGY][shade - 17.46k]]
- [[https://www.youtube.com/watch?v=z4zwlhUFs1Q][kaiser - 16.36k]]
**** occupied dance floor 2
30 mobs (post ignition version with better layout)

full clear: 14.28k
- [[https://youtu.be/TSyX2VC4JKE?t=1149][lara - full clear]]
- [[https://www.youtube.com/watch?v=W7gbTz3dJEY][night lord - full clear]]
**** victory plate street 1
30 mobs (post ignition version with better layout)

full clear: 14.28k
- [[https://www.youtube.com/watch?v=I7RR3uT1GHk][night lord - full clear]]
- [[https://www.youtube.com/watch?v=GiHRVweHIXY][lara - full clear]]
**** victory plate street 2
30 mobs (post ignition version with better layout)

full clear: 14.28k
- [[https://youtu.be/TSyX2VC4JKE?t=1405][lara - 14k]]
- [[https://www.youtube.com/watch?v=FI_4ymJ_mks][night lord - full clear]]
**** revelation place 1
30 mobs

full clear: 14.28k
- [[https://www.youtube.com/watch?v=etEPMr4FOeQ][lara - 13.1k]]
**** outlaw street 2
29 mobs

full clear: 13.8k
- [[https://www.youtube.com/watch?v=cz40ud71cC4][ice/lightning - 13.4k]]
**** occupied dance floor 1
28 mobs

full clear: 13.3k
- [[https://www.youtube.com/watch?v=Gdh-Fq61sIc][dawn warrior - full clear]]
*** arcana
[[https://seollal.tistory.com/1079?category=845748][mob counts (korean)]]
**** where water and sunlight meet
33 mobs. there's very few decent maps in arcana, this is one of them. also easy to loot without vac pet. if your rates in chickens 3 are good I would stay there until morass though

aliases: 물햇숲

full clear: 15.71k
- [[https://www.youtube.com/watch?v=vEsCt75RAP8][corsair - 15.6k]]
- [[https://www.youtube.com/watch?v=tM7mCsOv28E][shadower - 15.3k]] GMS, 2shot meso explosion
- [[https://www.youtube.com/watch?v=6RltfMKHcAY][paladin - 15k]]
- [[https://www.youtube.com/watch?v=CgD0Ls8Kxug][dark knight - 15k]]
- [[https://www.youtube.com/watch?v=ehbcBtkbnxI][angelic buster - 15.46k]] - 1shot soul seeker
- [[https://www.youtube.com/watch?v=YksT7Rf_js0][illium - 14k]]
- [[https://www.youtube.com/watch?v=PtBv0e3Te40][kinesis - 15.3k]]
**** deep in the cavern - upper path 1
32 mobs. seems pretty good for no vac pet.

aliases: dcup1, 동윗깊1

full clear: 15.2k
- [[https://www.youtube.com/watch?v=xrz8_T3A6nE][blaze wizard - full clear]] (pre-ignition but should be valid for post-ignition)
- [[https://www.youtube.com/watch?v=yuNMV1EwBuc][zero - full clear]]
- [[https://www.youtube.com/watch?v=2NpJnjSNUWQ][ark - 14.29k]]
- [[https://www.youtube.com/watch?v=0XSkF79XHhQ][buccaneer - 15.1k]]
- [[https://www.youtube.com/watch?v=r-HSxK-iMCQ][hero - 15k]]
- [[https://www.youtube.com/watch?v=SSHQHyFhyYs][mechanic - 14.6k]]
- [[https://www.youtube.com/watch?v=ZENUdES50EI][angelic buster - 14.98k]]
*** morass
[[https://seollal.tistory.com/1081?category=845748][mob counts (korean)]]
**** shadowdance hall 2
37 mobs, korean website is wrong about mob count on this one.
personal favorite. works for many classes, heard of people without vac pet still managing 16+k.
most of the mobs are on the left, so you want to proritize clearing those

aliases: sdh2, 그춤2

full clear: 17.61k
- [[https://youtu.be/ReBq0R1z18E?t=1437][shadower - 17.3k]] GMS, 1 hour BA, 2shot meso explosion
- [[https://youtu.be/bfmhwZtNykM?t=9][corsair - 17.5k]]
- [[https://www.youtube.com/watch?v=VmPjnPtNI2c][dawn warrior - 16.24k (30 mins BA)]]
- [[https://www.youtube.com/watch?v=NNWGeoTe9a0][dawn warrior - 16.4k]] - alternative rotation
- [[https://www.youtube.com/watch?v=mYCXj-_0qbk][night lord - 16.8k]] - 2shot mark
- [[https://www.youtube.com/watch?v=xXg55xhcBkU][night lord - 17k]] - 2shot mark
- [[https://www.youtube.com/watch?v=HMClgl9EO1c][lara - 17.3k]]
- [[https://www.youtube.com/watch?v=HwKKkA2xMAc][ark - 17k]]
**** shadowdance hall 3
good alternative if shadowdance 2 is full

aliases: sdh3, 그춤3

full clear: 17.61k
- [[https://youtu.be/2N2oIhzIX1E][corsair - 17k]]
- [[https://www.youtube.com/watch?v=cD-x2xv2p-c][adele - 17k]]
- [[https://www.youtube.com/watch?v=fgUbuLNJEmM][shadower - 17.5k]]
- [[https://www.youtube.com/watch?v=X4e0ApRXx14][illium - 16k]]
- [[https://www.youtube.com/watch?v=4DSRZ_i5V6A][wind archer - 16k]]
- [[https://www.youtube.com/watch?v=uzq6uRAvHsc][evan - 16.8k]]
**** abandoned area 2
37 mobs.

full clear: 17.61k
- [[https://www.youtube.com/watch?v=Oa_F7JKZ6Lo][night lord - 17.5k]]
- [[https://www.youtube.com/watch?v=j2KLu0Opn38][shade - 17.12k]]
- [[https://www.youtube.com/watch?v=kcEkPN6bMfw][buccaneer - full clear]] bucc's movement works great to walk up and down this triangular layout
- [[https://www.youtube.com/watch?v=f873OOHXUOA][zero - 17.3k]] zero's movement also works great to walk down these platforms
**** abandoned area 3
37 mobs.

full clear: 17.61k
- [[https://www.youtube.com/watch?v=RAokru5beq4][mercedes - 16.46k]]
- [[https://www.youtube.com/watch?v=x2ZPxgZy9mw][night walker - 16k]]
- [[https://www.youtube.com/watch?v=8XfIA0rNi4k][zero - 16k]]
- [[https://www.youtube.com/watch?v=s8SaWJKU1ZM][dawn warrior - 16k]]
- [[https://www.youtube.com/watch?v=UVPJcN74KkI][dual blade - 15.9k]]
- [[https://www.youtube.com/watch?v=sp2edJTKzl8][phantom - 17k]] 5s hat and strong arrow blaster. unrealistic for most players
- [[https://www.youtube.com/watch?v=oIqNOit4CYc][adele - 15.5k]]
**** that day in trueffet 3
35 mobs. good alternative if other maps are full. also somewhat less effort because of the drop down teleport

aliases: 그튀3, 그트3

full clear: 16.66k
- [[https://www.youtube.com/watch?v=SdSpLp2F5zg][ark - 15.3k]]
- [[https://www.youtube.com/watch?v=fc8Uc9F5cDQ][hoyoung - 15.4k]]
- [[https://www.youtube.com/watch?v=gWp9XExWK6A][cadena - full clear]]
- [[https://www.youtube.com/watch?v=7lw-xaRU0Bk][aran - 15.3k]]
*** esfera
[[https://seollal.tistory.com/1080?category=845748][mob counts (korean)]]
**** radiant temple 3
39 mobs. used to be the meta farming map. not anymore since we have sellas which is much easier to rotate

aliases: 신전3

full clear: 18.57k
- [[https://www.youtube.com/watch?v=FoBQOll8ZYk][ark - 15k]]
- [[https://www.youtube.com/watch?v=7wAk3zKy8no][bishop - 16.6k]]
- [[https://www.youtube.com/watch?v=QIdBvRF22Zo][bowmaster - 15.6k]]
- [[https://www.youtube.com/watch?v=Mml7L0lJhkM][shadower (pre-destiny) - full clear]]
**** living spring 6
38 mobs.

full clear: 18.09k

- [[https://www.youtube.com/watch?v=YH2gxOPYra8][corsair - 16.5k]]
- [[https://www.youtube.com/watch?v=fIf83YWxXvc][hoyoung - 17k]]
*** sellas
[[https://seollal.tistory.com/1111?category=845748][mob counts (korean)]]
**** the final edge of light 3
- [[https://www.youtube.com/watch?v=txbPQkEMJtw][corsair - 17.5k]]
**** plunging depths 3
- [[https://www.youtube.com/watch?v=NzP7WZNWUG0][corsair - 17k]]
*** moonbridge
[[https://seollal.tistory.com/1095?category=845748][mob counts (korean)]]
**** last horizon 6
38 mobs

full clear: 18.09k
- [[https://www.youtube.com/watch?v=xGHCJBgyyhg][corsair - full clear]]
- [[https://www.youtube.com/watch?v=ngllt2fAVGE][bowmaster - full clear]]
- [[https://www.youtube.com/watch?v=hRP4ALBB5Xk][dual blade - 17.5k]]
- [[https://www.youtube.com/watch?v=P3ASqLSdI4k][wind archer - 17.1k]]
- [[https://www.youtube.com/watch?v=WyqT71o4qoE][aran - full clear]]
- [[https://www.youtube.com/watch?v=CxOe0JmjfGk][marksman - full clear]]
- [[https://www.youtube.com/watch?v=8arziLfhq14][kain - full clear]]
- [[https://www.youtube.com/watch?v=xsJMVHqEbmA][adele - 18k]]
- [[https://www.youtube.com/watch?v=yCiKwf8D0oE][phantom - 16.5k]]
**** mysterious fog 3
37 mobs

full clear: 17.61k
- [[https://www.youtube.com/watch?v=5iEaICYHivE][corsair - full clear]]
- [[https://www.youtube.com/watch?v=Mau-5Ackwa8][corsair, lazy rotation using rapid fire - 15.5k]]
- [[https://www.youtube.com/watch?v=FgO_h6-pAIs][mercedes - 17.49k]]
- [[https://www.youtube.com/watch?v=7rVC0Ln0eWw][battle mage - 17.5k]]
- [[https://www.youtube.com/watch?v=sDBUgrWsXYg][marksman - 16.5k]]
- [[https://www.youtube.com/watch?v=77k7s2TEzxI][pathfinder - 16.5k]]
- [[https://www.youtube.com/watch?v=6ye9Dr1V_Ug][thunder breaker - 16.7k]]
**** mysterious fog 5
35 mobs

full clear: 16.66k
- [[https://www.youtube.com/watch?v=kKsUkDbOZGY][ice/lightning - 16.44k]]
*** labyrinth of suffering
[[https://seollal.tistory.com/1096?category=845748][mob counts (korean)]]
**** labyrinth of suffering core 6
35 mobs

full clear: 16.66k
- [[https://www.youtube.com/watch?v=4BjDemwY24c][corsair - full clear]]
- [[https://www.youtube.com/watch?v=3T7b7_NRwO8][dawn warrior - 16k]]
- [[https://www.youtube.com/watch?v=pBDBt-OtPHI][shadower - full clear]]
- [[https://www.youtube.com/watch?v=eMWyT1VOnV8][phantom - 16.4k]]
- [[https://www.youtube.com/watch?v=_4s7tQRcHDA][adele - full clear]]
- [[https://www.youtube.com/watch?v=D40948wTLkc][bowmaster - full clear]]
- [[https://www.youtube.com/watch?v=-gZsR_olDrE][aran - 16k]]
**** labyrinth of suffering core 4
37 mobs. website is wrong, checked shadower video

full clear: 17.61k
- [[https://www.youtube.com/watch?v=TGtFZyEPhbU][shadower - full clear]]
- [[https://www.youtube.com/watch?v=XtnZivje6AQ][wind archer - 17.55k]]
- [[https://www.youtube.com/watch?v=Ew6uQX66PH8][bowmaster - 16.6k]]
**** labyrinth of suffering core 5
the korean site says 29 mobs but based on videos I believe this to be at least 32 mobs

full clear: 15.2k?
- [[https://www.youtube.com/watch?v=r9XvggGDCGk][corsair - 15k]] - lazy rotation
- [[https://www.youtube.com/watch?v=bpDoLDGjhig][blaster - full clear]]
- [[https://www.youtube.com/watch?v=55Y3EiQJCXw][zero - full clear]]
- [[https://www.youtube.com/watch?v=HmA6H5HBFuc][dual blade - full clear]] pre-destiny
**** labyrinth of suffering core 1
34 mobs

full clear: 16.19k
- [[https://www.youtube.com/watch?v=fJ0RHpwkJQE][kinesis - 15.4k]]
*** limina
[[https://seollal.tistory.com/1097?category=845748][mob counts (korean)]]
**** end of the world 1-7
34 mobs, website is wrong. high arcane force, high exp per mob

full clear: 16.19k
- [[https://www.youtube.com/watch?v=RJXxzBnk5eE][night lord - full clear]]
- [[https://www.youtube.com/watch?v=q-kLEEld5fs][paladin - full clear]]
- [[https://www.youtube.com/watch?v=F5H6sCVjlXo][dawn warrior - 15.5k]]
- [[https://www.youtube.com/watch?v=SNPO_yQgb2M][ark - 15.99k]]
- [[https://www.youtube.com/watch?v=rnHhjYDiKF0][kaiser - 15.3k]]
- [[https://www.youtube.com/watch?v=zpUzb0xgao4][phantom - 15k]]
- [[https://www.youtube.com/watch?v=S5eS4Rrv-XE][adele - 15k]]
**** end of the world 1-6
34 mobs

full clear: 16.19k
- [[https://www.youtube.com/watch?v=rbzxODB-iQo][ark - 16k]]
- [[https://www.youtube.com/watch?v=PtjGTeXi0RY][buccaneer - 16k]]
- [[https://www.youtube.com/watch?v=6WupD0wMGeM][pathfinder - 16.41k]]
**** end of the world 2-5
32 mobs, really easy to loot without a vac pet, really lazy full clear

full clear: 15.23k
- [[https://www.youtube.com/watch?v=mn8VJNQSqug][thunder breaker - full clear]]
- [[https://www.youtube.com/watch?v=zKNjxGBXDC8][bishop - 15k]]
- [[https://www.youtube.com/watch?v=hzZOWoplNKQ][adele - full clear]]
**** end of the world 2-4
32 mobs

full clear: 15.23k
- [[https://www.youtube.com/watch?v=GSK2jEYv-UM][ice/lightning - full clear]]
**** end of the world 2-6
31 mobs, high arcane force, high exp per mob. better if you care about exp over meso/nodes

full clear: 14.7k
- [[https://www.youtube.com/watch?v=YH8gg0a9gV0][phantom - 14k]]
**** world sorrow's midpoint 1
35 mobs

full clear: 16.66k
- [[https://www.youtube.com/watch?v=GkqiA2euzd0][fire/poison - 14.99k]] lazy rotation
- [[https://www.youtube.com/watch?v=j3-728gVGMM][evan - 16.1k]] lazy rotation
**** world sorrow's midpoint 2
34 mobs

full clear: 16.19k
- [[https://www.youtube.com/watch?v=gvqsr66ZR-I][shadower - 15.7k]] lazy rotation
**** world sorrow's midpoint 3
34 mobs

full clear: 16.19k
- [[https://www.youtube.com/watch?v=SLMoao4I6Co][bishop - 16k]]
**** world sorrow's midpoint 4
34 mobs

full clear: 16.19k
- [[https://www.youtube.com/watch?v=7T6SGTIJKmw][zero - 14.2k]]
*** cernium
[[https://seollal.tistory.com/1111?category=845748][mob counts (korean)]]
**** cernium western city ramparts 3
38 mobs

full clear: 18.09k
**** rocky overlook 3
38 mobs

full clear: 18.09k
**** rocky overlook 4
38 mobs

full clear: 18.09k
**** cernium eastern city ramparts 3
37 mobs. high potential but weird layout

full clear: 17.61k
**** cernium easter city ramparts 2
33 mobs. not amazing mob count but easy layout that works for most classes

full clear: 15.7k
**** royal library section 3
37 mobs

full clear: 17.61k
**** royal library section 6
37 mobs

full clear: 17.61k
*** burning cernium
[[https://seollal.tistory.com/943?category=845748][mob counts (korean)]]

aliases: burnium
**** burning royal library section 6
38 mobs

full clear: 18.09k
**** burning royal library section 3
38 mobs

full clear: 18.09k
**** eastern city ramparts in battle 3
37 mobs

full clear: 17.61k
**** eastern city ramparts in battle 6
37 mobs

full clear: 17.61k
**** western city ramparts in battle 3
38 mobs

full clear: 18.09k
**** western city ramparts in battle 4
37 mobs

full clear: 17.61k
*** hotel arcus
[[https://seollal.tistory.com/549?category=845748][mob counts (korean)]]
**** nostalgic drive-in theater 6
38 mobs

full clear: 18.09k
**** outlaw-infested wastes 4
38 mobs

full clear: 18.09k
**** outlaw-infested wastes 3
37 mobs

full clear: 17.61k
**** nostalgic drive-in theater 3
37 mobs

full clear: 17.61k
*** odium
[[https://seollal.tistory.com/726?category=845748][mob counts (korean)]]
